# Config for running WANDB param-sweeps
# Reference: https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
# Create a sweep agent: `wandb sweep --project adv_nlp2023 conf/config.yaml`

program: main.py
method: grid # grid, bayes, random
parameters:
  wandb_mode :
    values : ["offline"]
  learning_rate:
    values:
      - 0.001
      - 0.0001
  optimizer:
    values: ["adam"]
metric:
  name: validation_loss # https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
  goal: minimize