# Config for running WANDB param-sweeps
# Reference: https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
# Create a sweep agent: wandb

program: main.py
method: grid # grid, bayes, random
parameters:
  learning_rate:
    values:
      - 0.001
      - 0.0001
  optimizer:
    values: ["adam"]
metric:
  name: validation_loss # remember to log val_loss https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
  goal: minimize
command:
  - $